#
# Makefile ESQUELETO
#
# DEVE ter uma regra "all" para geração da biblioteca
# regra "clean" para remover todos os objetos gerados.
#
# NECESSARIO adaptar este esqueleto de makefile para suas necessidades.
#
# 

CC=gcc
CFLAGS=-Wall -g
LIB_DIR=./lib
INC_DIR=./include
BIN_DIR=./bin
SRC_DIR=./src

all:



clean:
	rm -rf $(LIB_DIR)/*.a $(SRC_DIR)/*~ $(INC_DIR)/*~ *~ ; cp $(BIN_DIR)/bitmap2.o $(INC_DIR)/bitmap2.o ; cp $(BIN_DIR)/apidisk.o $(INC_DIR)/apidisk.o ; rm -rf $(BIN_DIR)/*.o ; mv $(INC_DIR)/apidisk.o $(BIN_DIR)/apidisk.o ; mv $(INC_DIR)/bitmap2.o $(BIN_DIR)/bitmap2.o


